// <auto-generated />
using System;
using ControlFamily.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConrolFamily.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230323211747_InitialIncomesTable")]
    partial class InitialIncomesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlFamily.Models.Expense", b =>
                {
                    b.Property<int>("IdExpense")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExpense"));

                    b.Property<double>("AmountExpense")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateExpense")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameExpense")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdExpense");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("ControlFamily.Models.Income", b =>
                {
                    b.Property<int>("IdIncome")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIncome"));

                    b.Property<double>("AmountIncome")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateIncome")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameIncome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdIncome");

                    b.ToTable("Incomes");
                });
#pragma warning restore 612, 618
        }
    }
}
